### ISSUE TITLE
Remove MongoDB dependency

### ISSUE THREAD

**Issue by codefromthecrypt** [hypertrace/entity-service#18]
Entity service is an extremely simple and can be served even by SQL. If this assumption is true, using MongoDB limits everyone to that tool, including its massive image size, and horrible logging controls. Can we please have another alternative?

**Comment by jcchavezs** [comment]
Could we list the features that potentially would be affected by the change?

**Comment by adriancole** [comment]
@jcchavezs I would expect people evaluating what alternatives could be used to need to look at what's exposed by the API though I'm not sure what part of it is really needed vs what is just mapping things that conveniently exist. The UI eventually (via GraphQL etc) use this

https://github.com/hypertrace/entity-service/blob/main/entity-service-api/src/main/proto/org/hypertrace/entity/query/service/v1/request.proto

**Comment by adriancole** [comment]
in general I think probably @buchi-busireddy can say what sort of things as he has familiarity in this. Main idea is I'm not sure entirely what is required. Beyond feature-mapping, existing operators would need to use a non-mongo client to play with data etc.

**Comment by adriancole** [comment]
in HT for those less familiar Entity is derived things from services like Backend Api Service

it isn't the timeseries data like spans, which are in pinot

**Comment by adriancole** [comment]
looking at the request personally, I'm a little scared but it is more about the flexibility offered vs what mongo can do specifically. It seems to allow nesting expressions. It may hint that a decision like this may require reversing which parts of that api are actually needed as infinite nesting is unlikely needed.

**Comment by naresh-a** [comment]
Yes, it looks like that entity service's related use-cases can be served by simpler relational DBs given the scale of this data and query patterns. We should lay down use-cases, data model requirements and query patterns to take an informed decision. May be, we can evaluate using an embedded DB as well (as an additional deployment option).

**Comment by adriancole** [comment]
here's one current impact. Unless you do external filtering, there's no way to get healthchecks from spamming the console. This is because Mongo allows you to reduce logging only to INFO (not WARN or OFF)

Ex. even with quiet
```Dockerfile
    # overrides normal entrypoint to quiet logs.
    command: ["mongod", "--quiet", "--bind_ip", "0.0.0.0"]
```

console is spammed unless you setup something else to externally filter (eg syslog or an external filtering tool)
```
mongo                           | 2020-08-28T00:08:16.457+0000 I NETWORK  [conn11] received client metadata from 127.0.0.1:47794 conn11: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.6" }, os: { type: "Linux", name: "NAME="Alpine Linux"", architecture: "x86_64", version: "Kernel 4.19.76-linuxkit" } }
mongo                           | 2020-08-28T00:08:16.461+0000 I NETWORK  [conn11] end connection 127.0.0.1:47794 (2 connections now open)
mongo                           | 2020-08-28T00:08:21.634+0000 I NETWORK  [conn12] received client metadata from 127.0.0.1:47830 conn12: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.6" }, os: { type: "Linux", name: "NAME="Alpine Linux"", architecture: "x86_64", version: "Kernel 4.19.76-linuxkit" } }
mongo                           | 2020-08-28T00:08:21.638+0000 I NETWORK  [conn12] end connection 127.0.0.1:47830 (2 connections now open)
mongo                           | 2020-08-28T00:08:26.783+0000 I NETWORK  [conn13] received client metadata from 127.0.0.1:47858 conn13: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.6" }, os: { type: "Linux", name: "NAME="Alpine Linux"", architecture: "x86_64", version: "Kernel 4.19.76-linuxkit" } }
mongo                           | 2020-08-28T00:08:26.788+0000 I NETWORK  [conn13] end connection 127.0.0.1:47858 (2 connections now open)
mongo                           | 2020-08-28T00:08:31.975+0000 I NETWORK  [conn14] received client metadata from 127.0.0.1:47892 conn14: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.6" }, os: { type: "Linux", name: "NAME="Alpine Linux"", architecture: "x86_64", version: "Kernel 4.19.76-linuxkit" } }
mongo                           | 2020-08-28T00:08:31.981+0000 I NETWORK  [conn14] end connection 127.0.0.1:47892 (2 connections now open)
```

Normal programs make things like access logging optional or configurable internally, presumably not just for the help of ops, but also to remove overhead of capturing them in the first place.

**Comment by kotharironak** [comment]
we now have PostgreSQL as another document store support.
