### ISSUE TITLE
Unable to filter based on non-attribute field

### ISSUE THREAD

**Issue by inespo** [hypertrace/entity-service#53]
Entity Service does not support filtering non-attribute fields without updating the code. 
An example is lastUpdateTime. 

createdTime is filterable because it has a special condition check in ```DocStoreConverter.isPartOfAttributeMap()```. 
This needs to be more generic to support all fields of the entity and not just limited to createdTime or attributes.<field-name> attributes.

**Comment by JBAhire** [comment]
@inespo, does https://github.com/hypertrace/entity-service/pull/54 fix this?
