### ISSUE TITLE
Supports an operation to check if an attribute exists or not

### ISSUE THREAD

**Issue by inespo** [hypertrace/entity-service#58]
Entity Service has an attribute field that's a map. However, there's no support to check if an attribute has been inserted or not into the map.

Document Store already support Exists operator, and it could be the solution it just exposes the operator and pass it down to Document store.

**Comment by kotharironak** [comment]
The use case here is to fetch entities on certain missing attributes.  As an example, 
`Select all APIs where state = xyz and dosn't have attribute.x`
